### PR TITLE
EDIT: added a line to hamza.html

### PR DESCRIPTION
**Pull request by hamza46awais**
Added a paragraph to hamza.html

### CODE REVIEW

**Comment by binkbop101** [comment]
Hello Hamza. This is poor work. Please find a checklist with regards to improving this work.

1. Delete this pull request.
2. Remove this code from your local repo.

**Comment by hamza46awais** [comment]
:(

**Comment by Nasimkrm** [comment]
Terrible

**Comment by binkbop101** [comment]
Awesome

**Pull request merged**
